[package]
name = "tshell"
version = "0.1.0"
authors = ["Teymur <teymur_baabyev08@yahoo.com>"]
edition = "2021"
build = "build.rs"

[build-dependencies]
embed-resource = "1.4"
rustyline = "12.0.0"
colored = "2.1.0"

[dependencies]
colored = "2.1.0"
rustyline = "12.0.0"
embed-resource = "1.4"
